version: "3.9"
services:
  db:
    image: mysql/mysql-server:latest
    # restart: always
    environment:
      MYSQL_DATABASE: 'streamapp'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'